[package]
name = "rust-vulkan-playground"
version = "0.1.0"
authors = ["Elmar Schug <elmar.schug@jayware.org>"]
edition = "2018"

[dependencies]
skyshard = { path = "lib/skyshard" }

log = "0.4.11"
log4rs = "0.13.0"
ash = "0.33.0"
ash-window = "0.7.0"
winit = "0.22.0"
png = "0.15.0"

[dev-dependencies]
hamcrest2 = "0.3.0"
