[package]
name = "rust-vulkan-playground"
version = "0.1.0"
authors = ["Elmar Schug <elmar.schug@jayware.org>"]
edition = "2018"

[dependencies]
log = "0.4.11"
log4rs = "0.13.0"
vulkano = "0.19.0"
vulkano-win = "0.19.0"
vulkano-shaders = "0.19.0"
winit = "0.22.0"
png = "0.15.0"
cgmath = "0.17.0"

[dev-dependencies]
hamcrest2 = "0.3.0"
