name: build
on: [push]

jobs:
  build:
    strategy:
      matrix:
        platform:
          - name: linux-x86_64
            os: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            binary: rust-vulkan-playground
            bundle: rust-vulkan-playground.tar.gz
          - name: windows-x86_64
            os: windows-2022
            target: x86_64-pc-windows-msvc
            binary: rust-vulkan-playground.exe
            bundle: rust-vulkan-playground.zip
    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@e96b7a80d708e231e7b958853ecf42169671fbc5
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@8504a5cb1826786b18ef7a8819e6fddaf9f3eb8d
        with:
          toolchain: stable
          targets: ${{ matrix.platform.target }}
      - name: Cache Toolchain
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: toolchain-${{ matrix.platform.target }}
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6
      - name: Cargo Fetch
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: fetch
      - name: Cargo Build (debug)
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: build
          args: --workspace
      - name: Cargo Test
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: test
          args: --workspace
      - name: Cargo Build (release)
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: build
          args: --workspace --release
      - name: Bundle
        run: |
          mkdir -p dist/rust-vulkan-playground
          cd dist
          cp -R ../assets/ rust-vulkan-playground/
          cp ../target/release/${{ matrix.platform.binary }} rust-vulkan-playground/
          cd -
        shell: bash
      - name: Archive (linux)
        if: contains(matrix.platform.name, 'linux')
        run: |
         cd dist
         tar czvf ${{ matrix.platform.bundle }} rust-vulkan-playground/
         cd -
        shell: bash
      - name: Archive (windows)
        if: contains(matrix.platform.name, 'windows')
        run: |
         cd dist
         7z a ${{ matrix.platform.bundle }} rust-vulkan-playground/
         cd -
        shell: bash
      - name: Upload Artifacts
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce
        with:
          name: ${{ matrix.platform.bundle }}
          path: dist/${{ matrix.platform.bundle }}
          retention-days: 7
