name: build
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@e96b7a80d708e231e7b958853ecf42169671fbc5
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f
        with:
          toolchain: stable
      - name: Cache Rust toolchain
        uses: actions/cache@48af2dc4a9e8278b89d7fa154b955c30c6aaab09
        with:
          path: |
            ~/.rustup/toolchains
            ~/.rustup/update-hashes
            ~/.rustup/settings.toml
          key: toolchain-${{ hashFiles('rust-toolchain') }}
      - name: Cache project dependencies
        uses: Swatinem/rust-cache@359a70e43a0bb8a13953b04a90f76428b4959bb6
      - name: Fetch
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: fetch
      - name: Build
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: build
          args: --workspace
      - name: Test
        uses: actions-rs/cargo@ae10961054e4aa8b4aa7dffede299aaf087aa33b
        with:
          command: test
          args: --workspace
